### ISSUE TITLE
Proposal credits not working

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2075] opened 2020-07-23 22:30 UTC
Bee reported that they bought proposal credits on mainnet and the credits were not properly credited to their account.  I poked around on test-proposals and used the admin rescan functionality for a couple of users.  Every user that I tried had missing credits that were added by the rescan.  Something is amiss.  This could be a backend issue, but the backend paywall code hasn't been touched in a long time.  Can we check if something weird is going on in the gui?

**Comment by xaur** [comment] 2020-07-25 20:25
Just for reference, rescan immediately fixed the issue for me on mainnet.

**Comment by tiagoalvesdulce** [comment] 2020-08-07 16:59
I don't think this issue is caused in the gui. I investigated the polling code and any issue that might happen there should be fixed with a simple refresh since we get the number of proposalcredits from the `/me` endpoint.

**Comment by thi4go** [comment] 2020-08-13 14:00
Dug in this and I was unable to reproduce the error. All scenarios of credit purchase I've tested were credited automatically to the account, or with a page refresh at maximum. None that needed a admin rescan to be shown. Anyhow, this is probably a backend issue. Can we go ahead and close this one @tiagoalvesdulce? I'm opening a new one on the BE so that we can keep track of this. thanks!

**Comment by tiagoalvesdulce** [comment] 2020-08-15 00:20
Ok, closing.

**Closed by tiagoalvesdulce** 2020-08-15 00:20 UTC
