### ISSUE TITLE
[cms] Make cursor pointer when editting accounts

### ISSUE THREAD

**Issue by vctt94** [decred/politeiagui#1965] opened 2020-06-01 16:18 UTC
When editing accounts, the icon to edit is small and may be not very visible, what can make it not very clear where need to be clicked for editing accounts.

I think making the cursor as pointer when hovering it would make it clearer.

![image](https://user-images.githubusercontent.com/15069783/83428661-37707800-a409-11ea-8241-bd7d628ba335.png)

**Comment by tiagoalvesdulce** [comment] 2020-06-02 12:36
Duplicate of https://github.com/decred/politeiagui/issues/1920

**Closed by tiagoalvesdulce** 2020-06-02 12:36 UTC
