### ISSUE TITLE
RFP dropdown menu

### ISSUE THREAD

**Issue by jzbz** [decred/politeiagui#2144] opened 2020-09-27 21:46 UTC
Might make sense to offer a dropdown menu showing currently running RFPs as opposed to getting submitters to paste in the RFP proposal hash.

![rfp](https://user-images.githubusercontent.com/4731927/94376494-dde33600-00e8-11eb-983d-df665798a88a.png)

**Comment by lukebp** [comment] 2020-09-27 22:28
Duplicate of #2139

**Closed by lukebp** 2020-09-27 22:28 UTC
