### ISSUE TITLE
'Read more' link improvement

### ISSUE THREAD

**Issue by s-ben** [decred/politeiagui#817] opened 2018-10-30 19:40 UTC
Every comment has a `Read more` link at the bottom, even if all the text is already displayed.
![image](https://user-images.githubusercontent.com/1634777/47745381-bfe0d280-dc40-11e8-9eef-2f0d639120d5.png)

This is minor, but annoying for new users. I just found myself clicking the `Read more` link a couple times, assuming there was more (as this is standard convention), only to have the `Read more` simply flip to `Read less` without the text changing.

**Comment by camus-code** [comment] 2018-10-31 17:55
Will fix this one up since I wrote the 'read more' code. Can I ask what browser you're using @s-ben ? I'm having some trouble reproducing it on my end with Firefox / Chrome

**Comment by s-ben** [comment] 2018-10-31 19:09
@camus-code , I'm using Brave (version 0.25.2). I'm actually having problems trying to recreate here actually. Tried logging in with Chrome to test there. Entered my correct password (almost positive), but got 'Action Needed' popup, which leads me to another pops that asks me to import my identity. Presumably this is correct behavior.
![image](https://user-images.githubusercontent.com/1634777/47812339-6098c600-dd05-11e8-97f4-b4f103e53a65.png)

And, when I try and re-recreate the issue in Brave, it appears to be gone. Here is the comment I screenshotted before, without the 'Read more' text showing up.
![image](https://user-images.githubusercontent.com/1634777/47812413-98077280-dd05-11e8-9013-6e0e1f2b9da1.png)

Not sure what happened, but if no one else has this issue, I can close Issue.

**Comment by camus-code** [comment] 2018-10-31 19:47
@s-ben Thanks for trying to test it. That message is indeed the correct behavior as it indicates since you switched browsers.

No need to close it as I'm sure it will keep popping up here and there. Not a huge priority right now but I'll refactor the code in the coming days for this button.

**Comment by xaur** [comment] 2018-11-02 13:42
I noticed something similar a few days ago and made a note:

> https://proposals.decred.org/proposals/27f87171d98b7923a1bd2bee6affed929fa2d2a6e178b5c80a9971a92a5c7f50 search "In that case" comment by nnnko56. If I click "Read more" nothing happens, same when clicking "Read less".

But now it is no longer reproducible.

**Comment by camus-code** [comment] 2018-11-02 15:53
Yup finally noticing the error on my end as well. It seems some comments are errantly being displayed with the read more button whenever there's nothing more to show.

Working on this now!

**Closed** 2018-11-06 17:28 UTC
