### ISSUE TITLE
Unvote works but doesn't decrement the vote count.

### ISSUE THREAD

**Issue by lolandhold** [decred/politeiagui#2513] opened 2021-07-31 16:50 UTC
Click to upvote a comment, change your mind, click on the same place to unvote. Unvote doesn't decrement the vote count in the UI. Refreshing the page shows the unvote worked.

Happens for both upvote and downvote.

**Comment by lukebp** [comment] 2021-07-31 18:55
This is a duplicate of #2467.  The fix will be deployed soon.

**Closed by lukebp** 2021-07-31 18:55 UTC
