### ISSUE TITLE
Password length requirement shows as undefined in UI

### ISSUE THREAD

**Issue by NerdsvilleCEO** [decred/politeiagui#725] opened 2018-10-16 23:21 UTC
When signing up for Politeia, it attempts to show the password length requirement (questionable but auditable in https://github.com/decred/politeiagui/issues/189), but it shows as undefined, see below:

![signup_error](https://user-images.githubusercontent.com/5251847/47052841-31684d80-d178-11e8-8323-84f88063b47b.png)

**Comment by camus-code** [comment] 2018-10-17 13:37
@NerdsvilleCEO What browser are you using? I'm having a hard time reproducing this one (tried in firefox, chrome and safari)

**Comment by NerdsvilleCEO** [comment] 2018-10-17 19:49
@camus-code this is on Chrome, but I know now the backend API through politeawww was unreachable when testing if that helps

**Comment by camus-code** [comment] 2018-10-17 19:55
Hmmm okay. Thanks for posting the issue. When you get another chance could you try and reproduce this problem? I'm still having issues getting it to render as undefined on my end.

**Comment by NerdsvilleCEO** [comment] 2018-10-17 20:05
I went ahead and reproduced this issue by doing the following:
  * Run politeiad, and then running politeiawww
  * Running the latest alpine docker image for the GUI
  * Try to sign up

**Comment by fernandoabolafio** [comment] 2018-10-18 18:07
hey, @NerdsvilleCEO thanks for reporting this issue. 
I have two questions:
1. All of this was seen in a local development env, right? 
2. When you refresh the page, does the error go away?

I've seen this a few times when you just started up politeiawww and it is still initializing, so the request which fetches the API policies fails and you get that undefined value in there.

**Comment by fernandoabolafio** [comment] 2018-10-22 19:21
I am closing as it looks like more a local setup issue rather than a system fail. If you need support on setting up your local env you can always contact us on the channel #politeia in Slack or Matrix.

**Closed by fernandoabolafio** 2018-10-22 19:21 UTC
