### ISSUE TITLE
Vote authorization cleared when logged in

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2308] opened 2021-03-15 21:36 UTC
1. I authorized voting for a proposal. Confirmation dialog showed up, OK, loading indicator, "success" message, "Authorize" button changed to "Revoke ..." - all as expected.

2. After a hard refresh (Ctrl-F5) it is again in unauthorized state "Waiting for author to authorize voting" on both In Discussion tab as well as the proposal page. The button is again "Authorize voting" (I guess I should not be pressing it again...).

3. If I open Politeia in a private tab (logged out), the status is proper "Waiting for admin to start voting". Must be a state issue in the logged-in tab.

**Comment by lukebp** [comment] 2021-03-15 21:43
Sounds like a gui issue related to the refresh.  If you opened it in a private tab and it said `Waiting for admin to start voting` then the authorization went through on the backend and the backend is returning the correct vote status for the proposal.

**Comment by xaur** [comment] 2021-03-15 22:18
I refreshed that same logged-in tab again after ~35 min (same login session) and the status is now correct. The sync eventually restored but it was slightly odd behavior.

**Comment by xaur** [comment] 2021-03-16 00:25
Another small observation: when the proposal moved from In Discussion to Voting, it still had "Waiting for admin to start voting" status, but it was short and it changed to the voting bar after a few refreshes.

**Comment by lukebp** [comment] 2021-03-16 00:55
Oh, I know what this is.  It will take up to 5 minutes for the proposal list views to reflect proposal state changes.

Decrediton added in a call in the 1.6 release that polls the proposals site every minute.  The problem is that when you have hundreds of wallets open, which happens when people leave their wallets open 24/7 for staking, you're sending hundreds of requests to politeia at the exact same time, low key DDoSing politeia.  The proposal list views are cached for 5 minutes to deal with the extra load until the polling is removed from decrediton.

It should only imapct the proposal list views, not  the proposal details pages.

**Comment by xaur** [comment] 2021-03-16 03:37
I'm pretty sure I observed this state issue on the proposal page too (state label and vote authorization button were wrong for some minutes).

**Comment by lukebp** [comment] 2021-03-16 13:31
It might be caching the vote status from the proposal details page.  I'd have to ask dhill.  The actual proposal contents (proposal files, comments) are definitely not being cached.

**Comment by lukebp** [comment] 2021-09-12 15:35
This was fixed in the v1.0.0 release and should not be present on the proposals site anymore.

**Closed by lukebp** 2021-09-12 15:35 UTC
