### ISSUE TITLE
[redesign] Drawer content needs to be aways on top of other elements

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1447] opened 2019-09-24 10:25 UTC
While testing test-proposals on a mobile device (Samsung s9) using Chrome browser. I noticed the drawer content is not consistently on top of the other elements:
![a55e1c86-752d-464f-8f19-a4facc286052](https://user-images.githubusercontent.com/14864439/65503776-e8f7fa80-dec5-11e9-8ad3-47b0398d99ba.jpeg)

**Comment by thi4go** [comment] 2019-09-24 15:33
On this

**Comment by thi4go** [comment] 2019-09-25 12:15
Hey @fernandoabolafio, I'm having some trouble reproducing this. Is there a specific context where this happens? On a proposal card with finished vote, for example?

**Comment by fernandoabolafio** [comment] 2019-09-26 08:30
@thi4go This happens to me on test-proposals.decred.org, in the "approved" tab when accessed from my cellphone.

**Comment by tiagoalvesdulce** [comment] 2019-10-09 13:15
@fernandoabolafio I couldn't reproduce it on my end as well.

**Comment by tiagoalvesdulce** [comment] 2019-10-25 15:14
Closing because I can't reproduce it. Feel free to reopen if more people are complaining about it.

**Closed by tiagoalvesdulce** 2019-10-25 15:14 UTC
Labels: Bug, Could not reproduce
