### ISSUE TITLE
Active tab indicator not changing

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1972] opened 2020-06-03 19:47 UTC
When I navigate from `In Discussion` tab to `Voting` tab, the content changes but the green line indicating the active tab does not.

Using Firefox.

![tab-not-changed-1](https://user-images.githubusercontent.com/24484727/83682086-f2983d00-a5d2-11ea-9c37-b22a1bc41046.png)
![tab-not-changed-2](https://user-images.githubusercontent.com/24484727/83682094-f62bc400-a5d2-11ea-972f-fe3016ccb741.png)

**Comment by lukebp** [comment] 2020-06-03 20:32
This cannot be reproduced on master.  We're about to do a production update in the next week or so with a lot of frontend changes.  There's a high likelihood that this already fixed so I'm closing this issue.  If you can reproduce it on test-proposals then we can open it back up, but we haven't been able to reproduce locally.

**Closed by lukebp** 2020-06-03 20:32 UTC

**Comment by xaur** [comment] 2020-06-04 22:29
Yeah I get the same on test-proposals:

![tab-testprops-1](https://user-images.githubusercontent.com/24484727/83816843-de2b7180-a6b2-11ea-961b-538f28797e79.png)
![tab-testprops-2](https://user-images.githubusercontent.com/24484727/83816847-e08dcb80-a6b2-11ea-88cb-979e562f7faa.png)

**Comment by tiagoalvesdulce** [comment] 2020-06-05 01:29
I couldn't repro this issue @xaur. Can you check if you have some extension that might be messing up with that? Or a custom config maybe...

**Comment by tiagoalvesdulce** [comment] 2020-06-09 20:11
I discussed with @xaur on matrix and found out that his setup is disabling some JS that `react-spring` use to do the animations.

**Comment by xaur** [comment] 2020-07-24 16:54
@tiagoalvesdulce FYI the new Flat Mode toggle does not change visually as well, might be the same cause. The feature does work though, i.e. comment ordering is toggled back and forth.

**Comment by amassarwi** [comment] 2020-07-24 17:48
@xaur 
All these issues are very specific to your setup, can't reproduce it here.

**Comment by xaur** [comment] 2020-07-24 17:55
@amassarwi yeah I don't think it will affect too many users. My setup is good at catching exotic js stuff though.

**Comment by amassarwi** [comment] 2020-07-24 17:59
my lord, let it rain

**Comment by lukebp** [comment] 2020-07-24 19:20
@xaur if an issue can't be reproduced in a normal browser setup we're not going to spend time on it.  It's not a good use of our time.  A no-js version of the site is being released soon so users will have the choice of the full-js site or the no-js alternative, but not something in between.
