### ISSUE TITLE
Text overflows the Before you sign up box

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#838] opened 2018-11-02 15:08 UTC
When I was signing up on Oct 26 I noticed this when resizing the browser window to be more narrow:

![20181026-signup-overflow](https://user-images.githubusercontent.com/24484727/47923369-20764680-deb1-11e8-80b0-f0f1d8449a0d.png)

**Comment by camus-code** [comment] 2018-11-05 19:17
I think this is a duplicate of #612 but still a problem nonetheless

Working on a fix now

**Comment by tiagoalvesdulce** [comment] 2018-11-05 22:44
Duplicate of https://github.com/decred/politeiagui/issues/612

**Closed by tiagoalvesdulce** 2018-11-05 22:44 UTC
